' ******************************************************************************
' swxJRNL.swj - journal recorded on 05/22/25 by Raman
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Dach_lcd6.89", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, -0.2815291967347381408, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.02124748654601797335, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.02655935818252246408, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.01593561490951347914, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, -0.04780684472854043743, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.01593561490951347914, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, -0.02655935818252246408, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, -0.04780684472854043743, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, -0.02124748654601797335, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.02124748654601797335, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, -0.02124748654601797335, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.02124748654601797335, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, -0.02124748654601797335, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.01062374327300898667, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, -0.04249497309203594669, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, -0.01593561490951347914, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, -0.02124748654601797335, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, -0.02124748654601797335, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, -0.01593561490951347914, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, -0.01593561490951347914, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, -0.02124748654601797335, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.02655935818252246408, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.01062374327300898667, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.01593561490951347914, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01546252634188729699, -0.02124748654601797335, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01546252634188729699, -0.01062374327300898667, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02577087723647883064, -0.02124748654601797335, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02319378951283094722, -0.01062374327300898667, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, -0.01062374327300898667, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01546252634188729699, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01546252634188729699, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0180396140655351804, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01546252634188729699, 0.01062374327300898667, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02319378951283094722, 0.01593561490951347914, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, 0.02124748654601797335, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02577087723647883064, 0.02655935818252246408, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, 0.03187122981902695829, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02577087723647883064, 0.03718310145553144902, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0180396140655351804, 0.02655935818252246408, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04381049130201401104, 0.06905433127455841424, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0180396140655351804, 0.03187122981902695829, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0180396140655351804, 0.03718310145553144902, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02319378951283094722, 0.05311871636504492816, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02834796496012671752, 0.06905433127455841424, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, 0.03718310145553144902, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0180396140655351804, 0.04780684472854043743, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, 0.03187122981902695829, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, 0.03718310145553144902, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.05311871636504492816, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, 0.04249497309203594669, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0.02124748654601797335, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.04780684472854043743, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.0584305880015494189, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0.04249497309203594669, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, 0.0584305880015494189, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0.04249497309203594669, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02655935818252246408, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04780684472854043743, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04249497309203594669, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04249497309203594669, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02655935818252246408, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03187122981902695829, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02655935818252246408, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03718310145553144902, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00257708772364788341, 0.03718310145553144902, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00257708772364788341, 0.02655935818252246408, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007731263170943648497, 0.04249497309203594669, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00257708772364788341, 0.03718310145553144902, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.04780684472854043743, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00257708772364788341, 0.02655935818252246408, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00257708772364788341, 0.01593561490951347914, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005154175447295766821, 0.02655935818252246408, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00257708772364788341, 0.01593561490951347914, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01062374327300898667, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00257708772364788341, 0.01593561490951347914, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01062374327300898667, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0180396140655351804, 0.01062374327300898667, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0180396140655351804, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, 0.01062374327300898667, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01546252634188729699, 0.01062374327300898667, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, 0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, 0.01062374327300898667, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01288543861823941532, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0180396140655351804, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00257708772364788341, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005154175447295766821, -0.005311871636504493337, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00257708772364788341, 0, 0.00916628972316857471, -0.006681362179676852975, -0.05165888843703214661

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06442719309119707138, 0.1274849192761078331, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02577087723647883064, 0.08498994618407189339, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.03187122981902695829, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007731263170943648497, 0.02655935818252246408, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01546252634188729699, 0.06374245963805391657, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.04780684472854043743, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01546252634188729699, 0.06905433127455841424, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01546252634188729699, 0.06905433127455841424, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, 0.08498994618407189339, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.03718310145553144902, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005154175447295766821, 0.03187122981902695829, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0180396140655351804, 0.06905433127455841424, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.05311871636504492816, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00257708772364788341, 0.03187122981902695829, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01288543861823941532, 0.06905433127455841424, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007731263170943648497, 0.05311871636504492816, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005154175447295766821, 0.02124748654601797335, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007731263170943648497, 0.04780684472854043743, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005154175447295766821, 0.03187122981902695829, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005154175447295766821, 0.04249497309203594669, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02655935818252246408, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02655935818252246408, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02124748654601797335, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02124748654601797335, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02124748654601797335, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01593561490951347914, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01593561490951347914, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01593561490951347914, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0.02124748654601797335, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01593561490951347914, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0.02124748654601797335, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0.02124748654601797335, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0.01593561490951347914, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0.01593561490951347914, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, 0.01593561490951347914, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, 0.01593561490951347914, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0.01593561490951347914, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, 0, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, 0, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, 0, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, 0, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, 0, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, 0, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, -0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.01593561490951347914, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0180396140655351804, -0.02655935818252246408, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.03187122981902695829, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01546252634188729699, -0.04249497309203594669, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, -0.04249497309203594669, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, -0.04249497309203594669, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0584305880015494189, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007731263170943648497, -0.04780684472854043743, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.04780684472854043743, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, -0.07436620291106289804, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.04780684472854043743, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.0584305880015494189, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005154175447295766821, -0.03718310145553144902, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.0584305880015494189, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.02124748654601797335, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.03187122981902695829, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.04780684472854043743, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02124748654601797335, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00257708772364788341, -0.03718310145553144902, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01593561490951347914, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03718310145553144902, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02124748654601797335, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01593561490951347914, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01062374327300898667, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005311871636504493337, 0.00491549426482440488, 0.03329999999994015525, 0.01124641183884023121

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
